language: bash

matrix:
  include:
    # macOS
    - os: osx
      compiler: clang
      script:
        - python test/run.py
        - make

    # Linux
    - os: linux
      dist: xenial
      script: 
        - python test/run.py
        - make
      env:
        - CC=gcc
        - CXX=g++

    # Clang + Linux disabled for now
    # - os: linux
    #   dist: xenial
    #   script: python test/run.py
    #   env:
    #     - CC=clang 
    #     - CXX=clang++

    # Windows
    - os: windows
      env:
        - CMAKE_PATH="/c/Program Files/CMake/bin"
      script: 
        - export PATH=$CMAKE_PATH:$PATH
        - python test/run.py
