image:
- Visual Studio 2017

install:
- cd C:\Tools\vcpkg
- git pull
- .\bootstrap-vcpkg.bat
- cd %APPVEYOR_BUILD_FOLDER%
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- vcpkg install zlib
- vcpkg install mbedtls
- cd test
- mkdir build
- cd build
- cmake -DUSE_TLS=1 -G"NMake Makefiles" ..
- nmake
- ixwebsocket_unittest.exe

cache: c:\tools\vcpkg\installed\

build: off
