name: unittest
on:
  push:
    paths-ignore:
    - 'docs/**'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: make test
      run: make test

  mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: make test
      run: make test

  win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: seanmiddleditch/gha-setup-vsdevenv@master
    - run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=cl.exe -DUSE_WS=1 -DUSE_TEST=1 ..
    - run: cmake --build build

    # Running the unittest does not work
    #- run: ../build/test/ixwebsocket_unittest.exe
    # working-directory: test
